Repository IBM/z_ansible_collections_samples, pull requests merged in 2020-09, with the labels that each got.

#13 Content/supplemental documentation
  README.md
  collections/requirements.yml
  docs/share/configuration_guide.md
  zos_administration/host_setup/README.md
  zos_administration/host_setup/filter_plugins/command_paths.py
  zos_administration/host_setup/filter_plugins/command_strings.py
  zos_administration/host_setup/host_setup.yaml
  zos_administration/host_setup/tasks/choose_python.yml
  zos_administration/host_setup/tasks/choose_zoau.yml
  zos_concepts/data_sets/copy_edit_submit/README.md
  zos_concepts/data_sets/copy_edit_submit/copy_edit_submit.yml
  zos_concepts/data_sets/data_set_basics/README.md
  zos_concepts/data_sets/data_set_basics/data_set_basics.yaml
  zos_concepts/data_transfer/copy_fetch_data_set/README.md
  zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
  zos_concepts/data_transfer/copy_sort_fetch/README.md
  zos_concepts/data_transfer/copy_sort_fetch/copy-sort-fetch.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/README.md
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/dump-pack-ftp.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/host_vars/destination.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/host_vars/source.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/transfer-data-sets.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/unpack-restore.yml
  zos_concepts/data_transfer/terse_fetch_data_set/README.md
  zos_concepts/data_transfer/terse_fetch_data_set/terse_fetch_data_set.yml
  zos_concepts/encoding/convert_encoding/README.md
  zos_concepts/encoding/convert_encoding/convert_encoding.yaml
  zos_concepts/jobs/submit_query_retrieve/README.md
  zos_concepts/jobs/submit_query_retrieve/submit_query_retrieve.yml
  zos_concepts/user_management/add_remove_user/README.md
  zos_concepts/user_management/add_remove_user/add-user.yml
  zos_concepts/user_management/add_remove_user/remove-user.yml
  zos_concepts/user_management/add_remove_user/send-rejection-email.yml
  zos_concepts/zos_operator/zos_operator_basics/README.md
  zos_concepts/zos_operator/zos_operator_basics/zos_operator_basics.yaml
Labels: documentation

#14 Updated minimum collection versions
  zos_administration/host_setup/filter_plugins/command_strings.py
  zos_administration/host_setup/tasks/choose_python.yml
  zos_administration/host_setup/tasks/choose_zoau.yml
  zos_concepts/data_sets/copy_edit_submit/copy_edit_submit.yml
  zos_concepts/data_sets/data_set_basics/data_set_basics.yaml
  zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/dump-pack-ftp.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/transfer-data-sets.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/unpack-restore.yml
  zos_concepts/data_transfer/terse_fetch_data_set/terse_fetch_data_set.yml
  zos_concepts/user_management/add_remove_user/add-user.yml
  zos_concepts/user_management/add_remove_user/remove-user.yml
  zos_concepts/user_management/add_remove_user/send-rejection-email.yml
  zos_concepts/zos_operator/zos_operator_basics/zos_operator_basics.yaml
Labels: documentation

#15 Update configuation guide with new layout and ordering
  docs/share/configuration_guide.md
Labels: documentation

#16 Updates to contribution statement and docs
  README.md
  zos_administration/host_setup/README.md
  zos_administration/host_setup/host_setup.yaml
  zos_concepts/data_sets/copy_edit_submit/README.md
  zos_concepts/data_sets/copy_edit_submit/copy_edit_submit.yml
  zos_concepts/data_sets/data_set_basics/README.md
  zos_concepts/data_sets/data_set_basics/data_set_basics.yaml
  zos_concepts/data_transfer/copy_fetch_data_set/README.md
  zos_concepts/data_transfer/copy_fetch_data_set/copy_fetch_data_set.yaml
  zos_concepts/data_transfer/copy_sort_fetch/README.md
  zos_concepts/data_transfer/copy_sort_fetch/copy-sort-fetch.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/README.md
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/dump-pack-ftp.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/transfer-data-sets.yml
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/unpack-restore.yml
  zos_concepts/data_transfer/terse_fetch_data_set/README.md
  zos_concepts/data_transfer/terse_fetch_data_set/terse_fetch_data_set.yml
  zos_concepts/encoding/convert_encoding/README.md
  zos_concepts/encoding/convert_encoding/convert_encoding.yaml
  zos_concepts/jobs/submit_query_retrieve/README.md
  zos_concepts/jobs/submit_query_retrieve/submit_query_retrieve.yml
  zos_concepts/user_management/add_remove_user/README.md
  zos_concepts/user_management/add_remove_user/add-user.yml
  zos_concepts/user_management/add_remove_user/remove-user.yml
  zos_concepts/user_management/add_remove_user/send-rejection-email.yml
  zos_concepts/zos_operator/zos_operator_basics/README.md
  zos_concepts/zos_operator/zos_operator_basics/zos_operator_basics.yaml
Labels: documentation

#17 Corrected bug where from_encoding and to_encoding were inverted
  zos_concepts/encoding/convert_encoding/convert_encoding.yaml
Labels: bug

#18 Content/updates to all readme
  zos_administration/host_setup/README.md
  zos_administration/host_setup/host_setup.yaml
  zos_administration/host_setup/inventory.yml
  zos_administration/host_setup/templates/test-vars.j2
  zos_concepts/data_sets/copy_edit_submit/README.md
  zos_concepts/data_sets/data_set_basics/README.md
  zos_concepts/data_transfer/copy_fetch_data_set/README.md
  zos_concepts/data_transfer/copy_sort_fetch/README.md
  zos_concepts/data_transfer/dump_pack_ftp_unpack_restore/README.md
  zos_concepts/data_transfer/terse_fetch_data_set/README.md
  zos_concepts/encoding/convert_encoding/README.md
  zos_concepts/jobs/submit_query_retrieve/README.md
  zos_concepts/user_management/add_remove_user/README.md
  zos_concepts/zos_operator/zos_operator_basics/README.md
Labels: bug, documentation

#19 Content/add git meta
  README.md
  meta/samples_repository/README.md
  meta/samples_repository/git-clone-pull-repo.yaml
Labels: documentation

#21 add user management blog to README
  README.md
Labels: documentation
