Repository IBM/z_ansible_collections_samples, pull requests merged in 2021-05, with the labels that each got.

#55 Sample playbooks for z/OSMF collection
  README.md
  zos_management.zip
  zos_management/zosmf_cloud_provisioning_and_management/README.md
  zos_management/zosmf_cloud_provisioning_and_management/ansible.cfg
  zos_management/zosmf_cloud_provisioning_and_management/cpm_manage_software_instance.yml
  zos_management/zosmf_cloud_provisioning_and_management/cpm_provision_software_service.yml
  zos_management/zosmf_cloud_provisioning_and_management/cpm_remove_software_instance.yml
  zos_management/zosmf_cloud_provisioning_and_management/host_vars/cpm_host1.yml
  zos_management/zosmf_cloud_provisioning_and_management/inventory.yml
  zos_management/zosmf_workflows/README.md
  zos_management/zosmf_workflows/ansible.cfg
  zos_management/zosmf_workflows/files/workflow_sample_automation_steps.xml
  zos_management/zosmf_workflows/group_vars/zos_systems.yml
  zos_management/zosmf_workflows/inventory.yml
  zos_management/zosmf_workflows/workflow_basic.yml
  zos_management/zosmf_workflows/workflow_complete.yml
Labels: Status: In Progress

#60 z/OSMF URI Sample
  README.md
  zos_concepts/rest_apis/README.md
  zos_concepts/rest_apis/ansible.cfg
  zos_concepts/rest_apis/files/sample_definition_file.xml
  zos_concepts/rest_apis/group_vars/all.yml
  zos_concepts/rest_apis/host_vars/zos_host.yml
  zos_concepts/rest_apis/inventories/zos_host
  zos_concepts/rest_apis/uri-sample.yml
Labels: Status: In Progress

#61 Mq samples
  README.md
  zos_subsystems/mq/README.md
  zos_subsystems/mq/mq.zip
  zos_subsystems/mq/mqsc/cfstruct/README.md
  zos_subsystems/mq/mqsc/cfstruct/host_vars/zos_host.yml
  zos_subsystems/mq/mqsc/cfstruct/inventory.yml
  zos_subsystems/mq/mqsc/cfstruct/mq_backup_cfstruct.yml
  zos_subsystems/mq/mqsc/qlocal/README.md
  zos_subsystems/mq/mqsc/qlocal/host_vars/zos_host.yml
  zos_subsystems/mq/mqsc/qlocal/inventory.yml
  zos_subsystems/mq/mqsc/qlocal/mq_alter_qlocal.yml
  zos_subsystems/mq/mqsc/qlocal/mq_define_qlocal.yml
  zos_subsystems/mq/mqsc/qlocal/mq_delete_qlocal.yml
  zos_subsystems/mq/mqsc/qlocal/mq_display_qlocal.yml
Labels: Status: Accepted

#63 Playbook to demonstrate parsing of a z/OS job response and use of Ansible constructs
  README.md
  zos_basics/constructs/README.md
  zos_basics/constructs/ansible.cfg
  zos_basics/constructs/files/HELLO.jcl
  zos_basics/constructs/inventory.yml
  zos_basics/constructs/zos_job_submit_ansible_constructs.yaml
Labels: Status: In Progress, Type: New Playbook
